version: '3'

services:
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=devroot
            - MONGO_INITDB_ROOT_PASSWORD=devroot
            - MONGO_INITDB_DATABASE=project
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
            - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            - ME_CONFIG_MONGODB_AUTH_USERNAME=devroot
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=devroot
            - ME_CONFIG_BASICAUTH_USERNAME=dev
            - ME_CONFIG_BASICAUTH_PASSWORD=dev
        depends_on:
            - mongo
        ports:
          - "8888:8081"



# version: '3'

# services:
#     mongo:
#         image: mongo
#         environment:
#             - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
#             - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#             - MONGO_INITDB_DATABASE=project
#     mongo-express:
#         image: mongo-express
#         environment:
#             - ME_CONFIG_MONGODB_SERVER=mongo
#             - ME_CONFIG_MONGODB_PORT=27017
#             - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
#             - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
#             - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
#             - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
#             - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
#             - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
#         depends_on:
#             - mongo
#         ports:
#           - "8888:8081"


# .env
# MONGO_ROOT_USER=devroot
# MONGO_ROOT_PASSWORD=devroot
# MONGOEXPRESS_LOGIN=dev
# MONGOEXPRESS_PASSWORD=dev